server:
  port: 8081
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
      password: Root123456
      username: root
      url: jdbc:mysql://rm-bp1k17lb43o44otnsbo.mysql.rds.aliyuncs.com:3306/questionnaire?characterEncoding=utf-8&userSSL=false
logging:
  level:
    com.neu: debug
  pattern:
    dateformat: mm:ss.SSS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true